# Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
sns.set()

# Load the data from a .csv in the same folder

In [2]:
row_data = pd.read_csv('admittance.csv')
row_data

      SAT Admitted
0    1363       No
1    1792      Yes
2    1954      Yes
3    1653       No
4    1593       No
..    ...      ...
163  1722      Yes
164  1750      Yes
165  1555       No
166  1524       No
167  1461       No

[168 rows x 2 columns]

# Change the column names to something more intuitive

In [3]:
data = row_data.copy()
data['Admitted'] = data['Admitted'].map({'No': 0, 'Yes': 1})
data

      SAT  Admitted
0    1363         0
1    1792         1
2    1954         1
3    1653         0
4    1593         0
..    ...       ...
163  1722         1
164  1750         1
165  1555         0
166  1524         0
167  1461         0

[168 rows x 2 columns]

# Declare the dependent and the independent variables

In [4]:
y = data['Admitted'] # dependent variable
x1 = data['SAT'] # independent variable

# Regression
## Add a constant to the independent variable

In [5]:
x = sm.add_constant(x1)
reg_logit = sm.Logit(y, x)
result_logit = reg_logit.fit()
result_logit.summary()

Optimization terminated successfully.
         Current function value: 0.137766
         Iterations 10

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      166
Method:                           MLE   Df Model:                            1
Date:                Mon, 16 Feb 2026   Pseudo R-squ.:                  0.7992
Time:                        14:35:57   Log-Likelihood:                -23.145
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 5.805e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -69.9128     15.737     -4.443      0.000    -100.756     -39.070
SAT            0.0420      0.009      4.454      0.000       0.024       0.060
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

#

# Accuracy of the model

In [6]:
result_logit.pred_table()

array([[67.,  7.],
       [ 7., 87.]])

In [7]:
cm_df = pd.DataFrame(result_logit.pred_table())
cm_df.columns = ['Predicted 0', 'Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0', 1: 'Actual 1'})
cm_df

          Predicted 0  Predicted 1
Actual 0         67.0          7.0
Actual 1          7.0         87.0

In [8]:
cm = np.array(cm_df)
accuracy_train = (cm[0,0] + cm[1,1]) / cm.sum()
accuracy_train

np.float64(0.9166666666666666)