In [24]:
import pandas as pd
import numpy as np
import datetime as dt

In [5]:
customers_data = pd.read_csv('customers.csv')
orders_data = pd.read_csv('orders.csv')
products_data = pd.read_csv('products.csv')
ratings_data = pd.read_csv('ratings.csv')
orders_data

     order_id  customer_id  product_id                  order_date  quantity
0           1           66          38  2023-08-09 08:39:23.971834         4
1           2           10          29  2023-09-08 08:39:23.971834         4
2           3           58           9  2023-07-29 08:39:23.971834         3
3           4           33          44  2023-09-13 08:39:23.971834         4
4           5           32          47  2023-07-24 08:39:23.971834         2
..        ...          ...         ...                         ...       ...
995       996           30          42  2023-08-15 08:39:23.971834         4
996       997            3          16  2023-09-11 08:39:23.971834         2
997       998           84          29  2023-09-05 08:39:23.971834         2
998       999           77          43  2023-08-13 08:39:23.971834         4
999      1000           19          32  2023-09-07 08:39:23.971834         3

[1000 rows x 5 columns]

# change the date column to datetime format

In [7]:
orders_data['order_date'] = pd.to_datetime(orders_data['order_date'])
orders_data

     order_id  customer_id  product_id                 order_date  quantity
0           1           66          38 2023-08-09 08:39:23.971834         4
1           2           10          29 2023-09-08 08:39:23.971834         4
2           3           58           9 2023-07-29 08:39:23.971834         3
3           4           33          44 2023-09-13 08:39:23.971834         4
4           5           32          47 2023-07-24 08:39:23.971834         2
..        ...          ...         ...                        ...       ...
995       996           30          42 2023-08-15 08:39:23.971834         4
996       997            3          16 2023-09-11 08:39:23.971834         2
997       998           84          29 2023-09-05 08:39:23.971834         2
998       999           77          43 2023-08-13 08:39:23.971834         4
999      1000           19          32 2023-09-07 08:39:23.971834         3

[1000 rows x 5 columns]

# Merge dataframes to create a comprehensive dataset

In [9]:
order_product=orders_data.merge(products_data, on="product_id")
order_product_customer=order_product.merge(customers_data, on="customer_id")
order_product_customer

,order_id,customer_id,product_id,order_date,quantity,product_name,price,category,name
0,1,66,38,2023-08-09 08:39:23.971834,4,Bekant Conference Table,441,Tables & Desks,Customer_66
1,2,10,29,2023-09-08 08:39:23.971834,4,Råskog Stool,855,Chairs,Customer_10
2,3,58,9,2023-07-29 08:39:23.971834,3,Micke Desk,19,Tables & Desks,Customer_58
3,4,33,44,2023-09-13 08:39:23.971834,4,Koppang Dresser,765,Decor,Customer_33
4,5,32,47,2023-07-24 08:39:23.971834,2,Nymö Lamp Shade,157,Lighting,Customer_32
...,...,...,...,...,...,...,...,...,...
995,996,30,42,2023-08-15 08:39:23.971834,4,Småstad Wardrobe,994,Storage Solutions,Customer_30
996,997,3,16,2023-09-11 08:39:23.971834,2,Ranarp Lamp,482,Lighting,Customer_3
997,998,84,29,2023-09-05 08:39:23.971834,2,Råskog Stool,855,Chairs,Customer_84
998,999,77,43,2023-08-13 08:39:23.971834,4,Sjöpenna Floor Lamp,187,Lighting,Customer_77
999,1000,19,32,2023-09-07 08:39:23.971834,3,Kivik Chaise,926,Sofas & Armchairs,Customer_19

# Calculating total revenue

In [10]:
product_performance = order_product_customer.groupby("product_name").agg({
    "price": "sum",
    "quantity": "sum"
}).reset_index()
product_performance

               product_name  price  quantity
0          Askvoll Wardrobe   3864        50
1   Bekant Conference Table  11907        62
2            Bernhard Chair   1280        36
3            Bestå TV Bench  18400        46
4            Billy Bookcase   5453        40
5       Brimnes Bed Storage  23190        77
6             Docksta Table  18039        54
7               Ektorp Sofa  14574        59
8        Fjälla Storage Box  18734        44
9               Fredde Desk  18854        46
10         Gronlid Armchair  12223        43
11         Hektar Work Lamp  10491        32
12            Hemnes Daybed  16900        53
13         Ingolf Bar Stool   9135        39
14             Ivar Cabinet  17862        55
15     Kallax Shelving Unit  15393        51
16             Kivik Chaise   9260        22
17         Klippan Loveseat  12141        52
18          Koppang Dresser  14535        48
19          Lack Side Table  13623        39
20            Lerhamn Chair   2375        41
21         Lommarp Bookcase  13760        41
22    Mackapar Shoe Storage  15114        80
23           Malm Bed Frame   4848        46
24    Melltorp Dining Table  10332        62
25               Micke Desk    304        43
26         Mörbylånga Table   5364        50
27             Nockeby Sofa  18101        58
28     Nordli Chest Drawers  12342        59
29          Nymö Lamp Shade   3297        46
30        Pjatteryd Picture  14300        41
31           Poäng Armchair  13656        63
32              Ranarp Lamp   9158        44
33           Raskog Trolley  10696        35
34       Rens Sheepskin Rug   9760        38
35              Ribba Frame   5184        37
36     Rugveda Coffee Table  16065        46
37             Råskog Stool  20520        59
38   Sinnerlig Pendant Lamp  11590        52
39      Sjöpenna Floor Lamp   3366        48
40      Skurup Ceiling Lamp   7308        49
41         Småstad Wardrobe  20874        52
42         Stockholm Mirror   6448        34
43     Strandmon Wing Chair   2050        61
44           Stuva Loft Bed   1455        32
45   Söderhamn Sofa Section  11691        63
46         Tarva Nightstand   7111        33
47      Terje Folding Chair  15466        44
48        Tingby Side Table   2071        48
49       Valje Wall Cabinet  16056        60

In [11]:
top_products_by_revenue =product_performance.sort_values(by="price", ascending=False)
top_products_by_quantity = product_performance.sort_values(by="quantity", ascending=False)

In [12]:
top_products_by_revenue

               product_name  price  quantity
5       Brimnes Bed Storage  23190        77
41         Småstad Wardrobe  20874        52
37             Råskog Stool  20520        59
9               Fredde Desk  18854        46
8        Fjälla Storage Box  18734        44
3            Bestå TV Bench  18400        46
27             Nockeby Sofa  18101        58
6             Docksta Table  18039        54
14             Ivar Cabinet  17862        55
12            Hemnes Daybed  16900        53
36     Rugveda Coffee Table  16065        46
49       Valje Wall Cabinet  16056        60
47      Terje Folding Chair  15466        44
15     Kallax Shelving Unit  15393        51
22    Mackapar Shoe Storage  15114        80
7               Ektorp Sofa  14574        59
18          Koppang Dresser  14535        48
30        Pjatteryd Picture  14300        41
21         Lommarp Bookcase  13760        41
31           Poäng Armchair  13656        63
19          Lack Side Table  13623        39
28     Nordli Chest Drawers  12342        59
10         Gronlid Armchair  12223        43
17         Klippan Loveseat  12141        52
1   Bekant Conference Table  11907        62
45   Söderhamn Sofa Section  11691        63
38   Sinnerlig Pendant Lamp  11590        52
33           Raskog Trolley  10696        35
11         Hektar Work Lamp  10491        32
24    Melltorp Dining Table  10332        62
34       Rens Sheepskin Rug   9760        38
16             Kivik Chaise   9260        22
32              Ranarp Lamp   9158        44
13         Ingolf Bar Stool   9135        39
40      Skurup Ceiling Lamp   7308        49
46         Tarva Nightstand   7111        33
42         Stockholm Mirror   6448        34
4            Billy Bookcase   5453        40
26         Mörbylånga Table   5364        50
35              Ribba Frame   5184        37
23           Malm Bed Frame   4848        46
0          Askvoll Wardrobe   3864        50
39      Sjöpenna Floor Lamp   3366        48
29          Nymö Lamp Shade   3297        46
20            Lerhamn Chair   2375        41
48        Tingby Side Table   2071        48
43     Strandmon Wing Chair   2050        61
44           Stuva Loft Bed   1455        32
2            Bernhard Chair   1280        36
25               Micke Desk    304        43

In [13]:
top_products_by_quantity

               product_name  price  quantity
22    Mackapar Shoe Storage  15114        80
5       Brimnes Bed Storage  23190        77
31           Poäng Armchair  13656        63
45   Söderhamn Sofa Section  11691        63
24    Melltorp Dining Table  10332        62
1   Bekant Conference Table  11907        62
43     Strandmon Wing Chair   2050        61
49       Valje Wall Cabinet  16056        60
7               Ektorp Sofa  14574        59
37             Råskog Stool  20520        59
28     Nordli Chest Drawers  12342        59
27             Nockeby Sofa  18101        58
14             Ivar Cabinet  17862        55
6             Docksta Table  18039        54
12            Hemnes Daybed  16900        53
17         Klippan Loveseat  12141        52
41         Småstad Wardrobe  20874        52
38   Sinnerlig Pendant Lamp  11590        52
15     Kallax Shelving Unit  15393        51
0          Askvoll Wardrobe   3864        50
26         Mörbylånga Table   5364        50
40      Skurup Ceiling Lamp   7308        49
18          Koppang Dresser  14535        48
39      Sjöpenna Floor Lamp   3366        48
48        Tingby Side Table   2071        48
23           Malm Bed Frame   4848        46
3            Bestå TV Bench  18400        46
36     Rugveda Coffee Table  16065        46
29          Nymö Lamp Shade   3297        46
9               Fredde Desk  18854        46
32              Ranarp Lamp   9158        44
47      Terje Folding Chair  15466        44
8        Fjälla Storage Box  18734        44
10         Gronlid Armchair  12223        43
25               Micke Desk    304        43
21         Lommarp Bookcase  13760        41
20            Lerhamn Chair   2375        41
30        Pjatteryd Picture  14300        41
4            Billy Bookcase   5453        40
19          Lack Side Table  13623        39
13         Ingolf Bar Stool   9135        39
34       Rens Sheepskin Rug   9760        38
35              Ribba Frame   5184        37
2            Bernhard Chair   1280        36
33           Raskog Trolley  10696        35
42         Stockholm Mirror   6448        34
46         Tarva Nightstand   7111        33
11         Hektar Work Lamp  10491        32
44           Stuva Loft Bed   1455        32
16             Kivik Chaise   9260        22

# Performance of products by month

In [23]:
last_month = order_product_customer[
    order_product_customer["order_date"].dt.month
    ==
    order_product_customer["order_date"].dt.month.max()]
top_clients_last_month = last_month.groupby("name").agg({
    "price": "sum"
}).reset_index()
top_clients_last_month = top_clients_last_month.sort_values(by="price", ascending=False)
top_clients_last_month

           name  price
0    Customer_1   5466
26  Customer_33   4476
38  Customer_44   4259
46  Customer_52   4236
71  Customer_76   3981
..          ...    ...
78  Customer_82    187
3   Customer_11    184
4   Customer_12    176
56  Customer_61    157
76  Customer_80     97

[96 rows x 2 columns]

# RFM analysis

In [30]:
latest_date = order_product_customer["order_date"].max() + dt.timedelta(days=1)
rfm = order_product_customer.groupby("customer_id").agg({
    "order_date": lambda x: (latest_date - x.max()).days,
    "order_id": "count",
    "price": "sum"
}).rename(columns={
    "order_date": "Recency",
    "order_id": "Frequency",
    "price": "Monetary"
})
rfm["recency_score"] = pd.qcut(rfm["Recency"], 5, labels=[5, 4, 3, 2, 1])
rfm["frequency_score"] = pd.qcut(rfm["Frequency"], 5, labels=[1, 2, 3, 4, 5])
rfm["monetary_score"] = pd.qcut(rfm["Monetary"], 5, labels=[1, 2, 3, 4, 5])
rfm["RFM_Score"] = (
                    rfm["recency_score"].astype(str)
                    + rfm["frequency_score"].astype(str)
                    + rfm["monetary_score"].astype(str)
                    )
rfm_sorted = rfm.sort_values(by="RFM_Score", ascending=False)
rfm_sorted

,Recency,Frequency,Monetary,recency_score,frequency_score,monetary_score,RFM_Score
customer_id,,,,,,,
1,1,18,12106,5,5,5,555
29,1,14,9225,5,5,5,555
52,1,16,8862,5,5,5,555
47,2,14,7385,5,5,5,555
33,2,15,8769,5,5,5,555
...,...,...,...,...,...,...,...
87,21,7,3502,1,1,1,111
79,16,3,2029,1,1,1,111
46,29,4,2488,1,1,1,111
13,12,6,3657,1,1,1,111
58,15,5,2324,1,1,1,111

# Review

In [39]:
top_review_products  = ratings_data.groupby("product_id").size().reset_index(name="num_reviews")
top_review_products  = top_review_products.merge(products_data, on="product_id")
top_review_products  = top_review_products.sort_values(by ="num_reviews", ascending=False)
review_per_customer = ratings_data.groupby("customer_id").size()
avg_review_per_customer = review_per_customer.mean()
print(top_review_products)
print(f"Average number of reviews per customer: {avg_review_per_customer:.2f}")

    product_id  num_reviews             product_name  price           category
11          12           16           Raskog Trolley    764  Storage Solutions
37          38           14  Bekant Conference Table    441     Tables & Desks
6            7           13          Lack Side Table    717     Tables & Desks
30          31           12             Nockeby Sofa    787  Sofas & Armchairs
16          17           11   Sinnerlig Pendant Lamp    610           Lighting
5            6           11      Brimnes Bed Storage    773               Beds
27          28           11         Tarva Nightstand    547              Decor
26          27           11             Ivar Cabinet    687  Storage Solutions
8            9           11               Micke Desk     19     Tables & Desks
31          32           11             Kivik Chaise    926  Sofas & Armchairs
29          30           11     Strandmon Wing Chair     82             Chairs
44          45           11         Hektar Work Lamp    807           Lighting
47          48           10           Bestå TV Bench    920              Decor
17          18           10      Skurup Ceiling Lamp    406           Lighting
13          14           10         Ingolf Bar Stool    609             Chairs
3            4           10           Malm Bed Frame    202               Beds
4            5           10            Hemnes Daybed    845               Beds
12          13            9      Terje Folding Chair    814             Chairs
36          37            9              Fredde Desk    857     Tables & Desks
38          39            9    Mackapar Shoe Storage    458  Storage Solutions
48          49            9   Söderhamn Sofa Section    433  Sofas & Armchairs
49          50            9         Mörbylånga Table    298     Tables & Desks
10          11            9           Billy Bookcase    287  Storage Solutions
39          40            8         Lommarp Bookcase    860  Storage Solutions
7            8            8    Melltorp Dining Table    369     Tables & Desks
33          34            8       Fjälla Storage Box    986  Storage Solutions
40          41            8        Tingby Side Table    109     Tables & Desks
43          44            7          Koppang Dresser    765              Decor
28          29            7             Råskog Stool    855             Chairs
45          46            7       Valje Wall Cabinet    669  Storage Solutions
41          42            7         Småstad Wardrobe    994  Storage Solutions
15          16            7              Ranarp Lamp    482           Lighting
25          26            7            Docksta Table    859     Tables & Desks
2            3            6         Klippan Loveseat    639  Sofas & Armchairs
20          21            6         Stockholm Mirror    496              Decor
18          19            6              Ribba Frame    324              Decor
19          20            6        Pjatteryd Picture    715              Decor
9           10            6     Kallax Shelving Unit    733  Storage Solutions
14          15            5           Bernhard Chair     80             Chairs
1            2            5           Poäng Armchair    569  Sofas & Armchairs
0            1            5              Ektorp Sofa    694  Sofas & Armchairs
21          22            5     Nordli Chest Drawers    561              Decor
23          24            5         Askvoll Wardrobe    184  Storage Solutions
22          23            5           Stuva Loft Bed     97               Beds
46          47            4          Nymö Lamp Shade    157           Lighting
35          36            4         Gronlid Armchair    719              Decor
34          35            3     Rugveda Coffee Table    765     Tables & Desks
32          33            3            Lerhamn Chair    125             Chairs
42          43            3      Sjöpenna Floor Lamp    187           Lighting
24          25            2       Rens Sheepskin Rug    610              Decor
Average number of reviews per customer: 4.04

In [44]:
product_reviews = ratings_data.groupby("product_id").agg({
    "rating" : ["count", "mean"]
}).reset_index()
product_reviews.columns = ["product_id", "num_reviews", "avg_rating"]
product_reviews = product_reviews.merge(products_data, on="product_id")
product_reviews_with_average_rating = product_reviews.sort_values(by="avg_rating", ascending=False)
product_reviews_with_average_rating

,product_id,num_reviews,avg_rating,product_name,price,category
24,25,2,4.500000,Rens Sheepskin Rug,610,Decor
19,20,6,4.166667,Pjatteryd Picture,715,Decor
3,4,10,3.900000,Malm Bed Frame,202,Beds
43,44,7,3.857143,Koppang Dresser,765,Decor
21,22,5,3.800000,Nordli Chest Drawers,561,Decor
13,14,10,3.800000,Ingolf Bar Stool,609,Chairs
36,37,9,3.777778,Fredde Desk,857,Tables & Desks
46,47,4,3.750000,Nymö Lamp Shade,157,Lighting
42,43,3,3.666667,Sjöpenna Floor Lamp,187,Lighting
49,50,9,3.666667,Mörbylånga Table,298,Tables & Desks
5,6,11,3.636364,Brimnes Bed Storage,773,Beds
22,23,5,3.600000,Stuva Loft Bed,97,Beds
44,45,11,3.454545,Hektar Work Lamp,807,Lighting
28,29,7,3.428571,Råskog Stool,855,Chairs
37,38,14,3.428571,Bekant Conference Table,441,Tables & Desks
10,11,9,3.222222,Billy Bookcase,287,Storage Solutions
14,15,5,3.200000,Bernhard Chair,80,Chairs
31,32,11,3.181818,Kivik Chaise,926,Sofas & Armchairs
9,10,6,3.166667,Kallax Shelving Unit,733,Storage Solutions
20,21,6,3.166667,Stockholm Mirror,496,Decor
15,16,7,3.142857,Ranarp Lamp,482,Lighting
47,48,10,3.100000,Bestå TV Bench,920,Decor
45,46,7,3.000000,Valje Wall Cabinet,669,Storage Solutions
32,33,3,3.000000,Lerhamn Chair,125,Chairs
26,27,11,3.000000,Ivar Cabinet,687,Storage Solutions
30,31,12,3.000000,Nockeby Sofa,787,Sofas & Armchairs
6,7,13,3.000000,Lack Side Table,717,Tables & Desks
12,13,9,3.000000,Terje Folding Chair,814,Chairs
1,2,5,3.000000,Poäng Armchair,569,Sofas & Armchairs
29,30,11,2.909091,Strandmon Wing Chair,82,Chairs
16,17,11,2.909091,Sinnerlig Pendant Lamp,610,Lighting
25,26,7,2.857143,Docksta Table,859,Tables & Desks
2,3,6,2.833333,Klippan Loveseat,639,Sofas & Armchairs
8,9,11,2.818182,Micke Desk,19,Tables & Desks
0,1,5,2.800000,Ektorp Sofa,694,Sofas & Armchairs
23,24,5,2.800000,Askvoll Wardrobe,184,Storage Solutions
48,49,9,2.777778,Söderhamn Sofa Section,433,Sofas & Armchairs
7,8,8,2.750000,Melltorp Dining Table,369,Tables & Desks
40,41,8,2.750000,Tingby Side Table,109,Tables & Desks
33,34,8,2.750000,Fjälla Storage Box,986,Storage Solutions
41,42,7,2.714286,Småstad Wardrobe,994,Storage Solutions
34,35,3,2.666667,Rugveda Coffee Table,765,Tables & Desks
18,19,6,2.666667,Ribba Frame,324,Decor
38,39,9,2.555556,Mackapar Shoe Storage,458,Storage Solutions
27,28,11,2.545455,Tarva Nightstand,547,Decor
4,5,10,2.500000,Hemnes Daybed,845,Beds
35,36,4,2.500000,Gronlid Armchair,719,Decor
11,12,16,2.312500,Raskog Trolley,764,Storage Solutions
17,18,10,2.300000,Skurup Ceiling Lamp,406,Lighting
39,40,8,1.750000,Lommarp Bookcase,860,Storage Solutions