# Patients Data Processing

In [3]:
import pandas as pd

# Load the data from the provided CSV file

In [4]:
raw_data = pd.read_csv('patients.csv')
# Display the first few rows of the dataset to understand its structure
raw_data.head()

   PatientID       Name  Age     Diagnosis  LabResult
0       1001  Patient_1   20      Diabetes        167
1       1002  Patient_2   74      Diabetes        153
2       1003  Patient_3   40  Hypertension        196
3       1004  Patient_4   23           NaN        157
4       1005  Patient_5   35      Diabetes        115

# 1. Data Cleaning:

In [5]:
raw_data["Diagnosis"] = raw_data["Diagnosis"].fillna("Unknown", inplace=True)
raw_data.drop_duplicates(inplace=True)
raw_data["Age"] = raw_data["Age"].astype(int)
raw_data = raw_data[raw_data["Age"] > 0]
raw_data["LabResult"] = raw_data["LabResult"].astype(int)
raw_data = raw_data[raw_data["LabResult"] > 0]

C:\Users\dasar\AppData\Local\Temp\ipykernel_11132\1496480897.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  raw_data["Diagnosis"] = raw_data["Diagnosis"].fillna("Unknown", inplace=True)

In [7]:
data_encoding = {diagnosis: idx for idx, diagnosis in enumerate(raw_data["Diagnosis"].unique())}
raw_data["Diagnosis_Encoded"] = raw_data["Diagnosis"].map(data_encoding)
raw_data.head()

   PatientID       Name  Age     Diagnosis  LabResult  Diagnosis_Encoded
0       1001  Patient_1   20      Diabetes        167                  0
1       1002  Patient_2   74      Diabetes        153                  0
2       1003  Patient_3   40  Hypertension        196                  1
3       1004  Patient_4   23       Unknown        157                  2
4       1005  Patient_5   35      Diabetes        115                  0